import { FlyingCard } from "flying.slint";
import { ReactiveCard } from "reactive.slint";
import { BasicCard } from "card.slint";

export component Root inherits Window {
	background: #202020;

	preferred-width: 400px;
	preferred-height: 600px;

	VerticalLayout {
		width: 60%;
		alignment: space-around;

		stack := ReactiveCard {
			id: -1;

			clicked => {
				flying.show = true;
				flying.flying = true;
			}
		}
		open := BasicCard {
			id: 42;
		}
	}

	flying := FlyingCard {
		id: 1;

		home_x: stack.absolute-position.x;
		home_y: stack.absolute-position.y;
		target_x: open.absolute-position.x;
		target_y: open.absolute-position.y;

		width: stack.width;
		height: stack.height;
	}
}
