import { BasicCard, CardMode } from "card.slint";

export component ReactiveCard inherits BasicCard {
    callback clicked();

    touch := TouchArea {
        clicked => {
        	if (root.mode != CardMode.Empty) {
        		root.clicked();
          }
        }
    }

    animate border-width, background {
        duration: 100ms;
        easing: ease-out;
    }

    circle := Rectangle {
        border-radius: self.width / 2;
        background: #808080;
        x: touch.pressed-x - self.width / 2;
        y: touch.pressed-y - self.height / 2;
    }

    states [
        active when touch.pressed && self.mode != CardMode.Empty: {
            circle.opacity: 30%;
            circle.width: 100px;
            circle.height: 100px;
            root.background: #084858;
            root.border-width: 5px;
            in {
                animate circle.width, circle.height {
                    duration: 1s;
                    easing: ease-out;
                }
            }
        }
        hover when touch.has-hover && self.mode != CardMode.Empty: {
            circle.opacity: 0;
            circle.width: 30px;
            circle.height: 30px;
            root.background: #175767;
            root.border-width: 5px;
        }
        idle when !touch.pressed && !touch.has-hover && self.mode != CardMode.Empty: {
            circle.opacity: 0;
            circle.width: 30px;
            circle.height: 30px;
            root.border-width: 0;
        }
    ]
}
